/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        background: "#fbf9f6",
        "on-background": "#1b1c1a",
        "on-secondary-fixed": "#351000",
        "secondary-fixed": "#ffdbcc",
        "surface-container-highest": "#e4e2df",
        "on-tertiary-fixed": "#3a0a00",
        "surface-container-low": "#f5f3f0",
        tertiary: "#983311",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeeeb",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#76330d",
        "surface-container-high": "#eae8e5",
        "secondary-fixed-dim": "#ffb693",
        "secondary-container": "#fd9e70",
        "on-primary-fixed": "#390c00",
        "surface-tint": "#ac3400",
        "tertiary-fixed-dim": "#ffb59f",
        "tertiary-container": "#b94a27",
        "on-primary-container": "#ffece7",
        "tertiary-fixed": "#ffdbd1",
        secondary: "#944a23",
        "primary-container": "#c2410c",
        "on-tertiary-fixed-variant": "#842503",
        "inverse-primary": "#ffb59d",
        "inverse-surface": "#30312f",
        "primary-fixed": "#ffdbd0",
        "on-tertiary-container": "#ffede8",
        "surface-variant": "#e4e2df",
        "on-surface": "#1b1c1a",
        "outline-variant": "#e1bfb5",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb59d",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad7",
        "on-surface-variant": "#59413a",
        outline: "#8d7168",
        "inverse-on-surface": "#f2f0ed",
        "surface-bright": "#fbf9f6",
        primary: "#9b2f00",
        surface: "#fbf9f6",
        "on-primary-fixed-variant": "#832600",
        "on-secondary-container": "#76340e"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-lg": "2rem",
        "space-xl": "3.5rem",
        margin: "4rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "margin-mobile": "1.25rem",
        gutter: "2rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "display-hero-mobile": ["Syne", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "label-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "body-xl": ["Be Vietnam Pro", "sans-serif"],
        "display-hero": ["Syne", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
};
